### ISSUE TITLE
Add project to packages.fhir.org

### ISSUE THREAD

**Issue by peturv** [commonprofiles-care/fhir#54]
We need to add a PR to the ig-registry project to be included in the central registry.

**Comment by peturv** [comment]
Until this is done we need to refer to the dependency by uri:
```
dependencies:
  care.commonprofiles.fhir:
    uri: https://commonprofiles.care/fhir
    version: 1.0.0
```
